### higher order functions, numpy, pandas

In [0]:
def calculate_sq(num_list):
    sq_list= []
    # we iterated on all the elements on the iterable (list)
    for num in num_list:
        sq_list.append(num**2)
    return sq_list

In [0]:
list_1= [1,2,3,4,5]
sq_num_list= calculate_sq(list_1)
print(sq_num_list)

[1, 4, 9, 16, 25]

In [0]:
# fucntions -  objects ==> first class citizens --> functions can be passed as arguments to other functions
# higher order fucntions --> functions as one of the arguemnets , iterables as another argument
# example- map(), reduce(), filter() etc..
 
def calculate_sq(list_1):
  sq_num_list=[]
  for i in list_1:
    sq_num_list.append(i*i)
  return sq_num_list

In [0]:
numbers= [10,12,33,67,90]
print(list(map(lambda x: x*x, numbers)))

[100, 144, 1089, 4489, 8100]

In [0]:
numbers = [1,2,3,4,5,6,7,8,9,10]

even_num_list= filter(lambda num: num%2==0, numbers)
print(list(even_num_list))

[2, 4, 6, 8, 10]

Docstring:
reduce(function, iterable[, initial]) -> value

Apply a function of two arguments cumulatively to the items of a sequence
or iterable, from left to right, so as to reduce the iterable to a single
value.  For example, reduce(lambda x, y: x+y, [1, 2, 3, 4, 5]) calculates
((((1+2)+3)+4)+5).  If initial is present, it is placed before the items
of the iterable in the calculation, and serves as a default when the
iterable is empty.
Type:      builtin_function_or_method

In [0]:
from functools import reduce

numbers = [1,2,3,4,5,6,7,8,9,10]
total = reduce(lambda x,y: x+y, numbers)
print("sum of numbers is ", total)

sum of numbers is  55

##### reduce()
##### e-comexamples -> purchasee 3 prodcuts -- prices
##### prices  =[100,300,670], 5% disc , purchase 6 product -> 10% disc
 
##### total amount= num of items & discount

In [0]:
from functools import reduce
 
prices = list(map(float, input("Enter prices of products separated by spaces: ").split()))
num_items = len(prices)
 
total = reduce(lambda x, y: x + y, prices)
 
if num_items >= 6:
    discount = 0.10
else:
    discount = 0.05
 
final_amount = total * (1 - discount)
 
print("Number of items:", num_items)
print("Total before discount:", total)
print("Discount applied:", f"{int(discount*100)}%")
print("Final amount after discount:", final_amount)

Enter prices of products separated by spaces:  66 77 88 99

Number of items: 4
Total before discount: 330.0
Discount applied: 5%
Final amount after discount: 313.5

In [0]:
raw_emails = [
    "john.doe@example.com",
    "jane_doe123@company.co",
    "noatsymbol.com",
    "user@domain",
    "alice@wonderland.org",
    "bob@site",
    "charlie@site.com"
]
 
def is_valid_email(email):
    return "@" in email and "." in email.split("@")[-1]
 
valid_emails = list(filter(is_valid_email, raw_emails))
print("Valid emails:", valid_emails)

Valid emails: ['john.doe@example.com', 'jane_doe123@company.co', 'alice@wonderland.org', 'charlie@site.com']

In [0]:
# pandas - the data (structured data, semi-structured data) --> table like structure 
# dataframe

In [0]:
import pandas as pd
emp_data= {
    'names': ['John', 'Mary', 'Jane'],
    'salary': [50000, 60000, 70000],
    'department': ['IT', ' HR', 'finance']
}
df = pd.DataFrame(emp_data)
df

  names  salary department
0  John   50000         IT
1  Mary   60000         HR
2  Jane   70000    finance

In [0]:
df.describe()

        salary
count      3.0
mean   60000.0
std    10000.0
min    50000.0
25%    55000.0
50%    60000.0
75%    65000.0
max    70000.0

In [0]:
type(df)

pandas.core.frame.DataFrame

In [0]:
# Data Profiling

In [0]:
%fs ls dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/

path,name,size,modificationTime
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2009-01.csv.gz,yellow_tripdata_2009-01.csv.gz,504262564,1596568279000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2009-02.csv.gz,yellow_tripdata_2009-02.csv.gz,480034681,1596568279000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2009-03.csv.gz,yellow_tripdata_2009-03.csv.gz,521102719,1596568279000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2009-04.csv.gz,yellow_tripdata_2009-04.csv.gz,515435466,1596568279000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2009-05.csv.gz,yellow_tripdata_2009-05.csv.gz,531133739,1596568279000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2009-06.csv.gz,yellow_tripdata_2009-06.csv.gz,508802995,1596568313000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2009-07.csv.gz,yellow_tripdata_2009-07.csv.gz,487731497,1596568318000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2009-08.csv.gz,yellow_tripdata_2009-08.csv.gz,490825210,1596568318000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2009-09.csv.gz,yellow_tripdata_2009-09.csv.gz,503121179,1596568318000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2009-10.csv.gz,yellow_tripdata_2009-10.csv.gz,567109604,1596568319000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2009-11.csv.gz,yellow_tripdata_2009-11.csv.gz,520260634,1596568351000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2009-12.csv.gz,yellow_tripdata_2009-12.csv.gz,530726595,1596568354000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2010-01.csv.gz,yellow_tripdata_2010-01.csv.gz,565548417,1596568356000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2010-02.csv.gz,yellow_tripdata_2010-02.csv.gz,396576504,1596568357000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2010-03.csv.gz,yellow_tripdata_2010-03.csv.gz,456086101,1596568363000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2010-04.csv.gz,yellow_tripdata_2010-04.csv.gz,579400917,1596568386000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2010-05.csv.gz,yellow_tripdata_2010-05.csv.gz,593525883,1596568389000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2010-06.csv.gz,yellow_tripdata_2010-06.csv.gz,568228308,1596568393000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2010-07.csv.gz,yellow_tripdata_2010-07.csv.gz,562093150,1596568396000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2010-08.csv.gz,yellow_tripdata_2010-08.csv.gz,441394152,1596568396000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2010-09.csv.gz,yellow_tripdata_2010-09.csv.gz,560174405,1596568429000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2010-10.csv.gz,yellow_tripdata_2010-10.csv.gz,515205924,1596568429000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2010-11.csv.gz,yellow_tripdata_2010-11.csv.gz,490723375,1596568432000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2010-12.csv.gz,yellow_tripdata_2010-12.csv.gz,489442107,1596568434000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2011-01.csv.gz,yellow_tripdata_2011-01.csv.gz,468994648,1596568437000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2011-02.csv.gz,yellow_tripdata_2011-02.csv.gz,500480531,1596568470000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2011-03.csv.gz,yellow_tripdata_2011-03.csv.gz,562171945,1596568472000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2011-04.csv.gz,yellow_tripdata_2011-04.csv.gz,516464131,1596568472000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2011-05.csv.gz,yellow_tripdata_2011-05.csv.gz,547466370,1596568473000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2011-06.csv.gz,yellow_tripdata_2011-06.csv.gz,533561250,1596568474000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2011-07.csv.gz,yellow_tripdata_2011-07.csv.gz,511667361,1596568507000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2011-08.csv.gz,yellow_tripdata_2011-08.csv.gz,479496009,1596568510000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2011-09.csv.gz,yellow_tripdata_2011-09.csv.gz,519067867,1596568513000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2011-10.csv.gz,yellow_tripdata_2011-10.csv.gz,555546037,1596568514000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2011-11.csv.gz,yellow_tripdata_2011-11.csv.gz,505934258,1596568514000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2011-12.csv.gz,yellow_tripdata_2011-12.csv.gz,521194284,1596568545000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2012-01.csv.gz,yellow_tripdata_2012-01.csv.gz,542699629,1596568547000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2012-02.csv.gz,yellow_tripdata_2012-02.csv.gz,538161783,1596568551000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2012-03.csv.gz,yellow_tripdata_2012-03.csv.gz,577176001,1596568552000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2012-04.csv.gz,yellow_tripdata_2012-04.csv.gz,543801972,1596568555000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2012-05.csv.gz,yellow_tripdata_2012-05.csv.gz,549759424,1596568584000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2012-06.csv.gz,yellow_tripdata_2012-06.csv.gz,536119707,1596568587000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2012-07.csv.gz,yellow_tripdata_2012-07.csv.gz,509555120,1596568591000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2012-08.csv.gz,yellow_tripdata_2012-08.csv.gz,511483352,1596568595000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2012-09.csv.gz,yellow_tripdata_2012-09.csv.gz,459381547,1596568597000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2012-10.csv.gz,yellow_tripdata_2012-10.csv.gz,468143217,1596568626000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2012-11.csv.gz,yellow_tripdata_2012-11.csv.gz,443832708,1596568628000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2012-12.csv.gz,yellow_tripdata_2012-12.csv.gz,493139441,1596568630000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2013-01.csv.gz,yellow_tripdata_2013-01.csv.gz,478262343,1596568632000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2013-02.csv.gz,yellow_tripdata_2013-02.csv.gz,451683985,1596568634000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2013-03.csv.gz,yellow_tripdata_2013-03.csv.gz,516448368,1596568662000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2013-04.csv.gz,yellow_tripdata_2013-04.csv.gz,500106589,1596568662000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2013-05.csv.gz,yellow_tripdata_2013-05.csv.gz,493978775,1596568667000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2013-06.csv.gz,yellow_tripdata_2013-06.csv.gz,472703135,1596568668000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2013-07.csv.gz,yellow_tripdata_2013-07.csv.gz,450013796,1596568668000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2013-08.csv.gz,yellow_tripdata_2013-08.csv.gz,421885789,1596568701000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2013-09.csv.gz,yellow_tripdata_2013-09.csv.gz,481546619,1596568702000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2013-10.csv.gz,yellow_tripdata_2013-10.csv.gz,500785608,1596568704000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2013-11.csv.gz,yellow_tripdata_2013-11.csv.gz,481124327,1596568705000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2013-12.csv.gz,yellow_tripdata_2013-12.csv.gz,459830158,1596568705000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2014-01.csv.gz,yellow_tripdata_2014-01.csv.gz,445284946,1596568734000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2014-02.csv.gz,yellow_tripdata_2014-02.csv.gz,427962052,1596568739000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2014-03.csv.gz,yellow_tripdata_2014-03.csv.gz,512115757,1596568742000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2014-04.csv.gz,yellow_tripdata_2014-04.csv.gz,475749569,1596568743000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2014-05.csv.gz,yellow_tripdata_2014-05.csv.gz,485741383,1596568743000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2014-06.csv.gz,yellow_tripdata_2014-06.csv.gz,456035000,1596568768000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2014-07.csv.gz,yellow_tripdata_2014-07.csv.gz,425991155,1596568772000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2014-08.csv.gz,yellow_tripdata_2014-08.csv.gz,419345164,1596568779000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2014-09.csv.gz,yellow_tripdata_2014-09.csv.gz,443182114,1596568780000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2014-10.csv.gz,yellow_tripdata_2014-10.csv.gz,466041865,1596568780000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2014-11.csv.gz,yellow_tripdata_2014-11.csv.gz,437336437,1596568803000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2014-12.csv.gz,yellow_tripdata_2014-12.csv.gz,431611778,1596568804000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2015-01.csv.gz,yellow_tripdata_2015-01.csv.gz,510982711,1596568811000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2015-02.csv.gz,yellow_tripdata_2015-02.csv.gz,498934977,1596568813000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2015-03.csv.gz,yellow_tripdata_2015-03.csv.gz,536626429,1596568815000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2015-04.csv.gz,yellow_tripdata_2015-04.csv.gz,526278868,1596568837000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2015-05.csv.gz,yellow_tripdata_2015-05.csv.gz,528674128,1596568837000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2015-06.csv.gz,yellow_tripdata_2015-06.csv.gz,484887977,1596568850000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2015-07.csv.gz,yellow_tripdata_2015-07.csv.gz,448653527,1596568852000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2015-08.csv.gz,yellow_tripdata_2015-08.csv.gz,432743918,1596568855000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2015-09.csv.gz,yellow_tripdata_2015-09.csv.gz,436791892,1596568877000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2015-10.csv.gz,yellow_tripdata_2015-10.csv.gz,478620813,1596568878000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2015-11.csv.gz,yellow_tripdata_2015-11.csv.gz,439257795,1596568887000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2015-12.csv.gz,yellow_tripdata_2015-12.csv.gz,445153178,1596568888000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2016-01.csv.gz,yellow_tripdata_2016-01.csv.gz,421734912,1596568890000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2016-02.csv.gz,yellow_tripdata_2016-02.csv.gz,439029046,1596568911000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2016-03.csv.gz,yellow_tripdata_2016-03.csv.gz,472243929,1596568915000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2016-04.csv.gz,yellow_tripdata_2016-04.csv.gz,463706594,1596568921000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2016-05.csv.gz,yellow_tripdata_2016-05.csv.gz,463046642,1596568921000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2016-06.csv.gz,yellow_tripdata_2016-06.csv.gz,435640067,1596568922000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2016-07.csv.gz,yellow_tripdata_2016-07.csv.gz,155772486,1596568946000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2016-08.csv.gz,yellow_tripdata_2016-08.csv.gz,149189301,1596568951000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2016-09.csv.gz,yellow_tripdata_2016-09.csv.gz,154436403,1596568955000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2016-10.csv.gz,yellow_tripdata_2016-10.csv.gz,164098675,1596568956000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2016-11.csv.gz,yellow_tripdata_2016-11.csv.gz,152816358,1596568956000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2016-12.csv.gz,yellow_tripdata_2016-12.csv.gz,157413907,1596568957000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2017-01.csv.gz,yellow_tripdata_2017-01.csv.gz,144492027,1596568962000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2017-02.csv.gz,yellow_tripdata_2017-02.csv.gz,136659107,1596568967000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2017-03.csv.gz,yellow_tripdata_2017-03.csv.gz,154604320,1596568968000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2017-04.csv.gz,yellow_tripdata_2017-04.csv.gz,150995632,1596568968000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2017-05.csv.gz,yellow_tripdata_2017-05.csv.gz,152513179,1596568969000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2017-06.csv.gz,yellow_tripdata_2017-06.csv.gz,144967379,1596568974000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2017-07.csv.gz,yellow_tripdata_2017-07.csv.gz,141141934,1596568977000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2017-08.csv.gz,yellow_tripdata_2017-08.csv.gz,138415411,1596568980000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2017-09.csv.gz,yellow_tripdata_2017-09.csv.gz,147622574,1596568980000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2017-10.csv.gz,yellow_tripdata_2017-10.csv.gz,160943166,1596568980000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2017-11.csv.gz,yellow_tripdata_2017-11.csv.gz,152770049,1596568986000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2017-12.csv.gz,yellow_tripdata_2017-12.csv.gz,156184671,1596568989000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2018-01.csv.gz,yellow_tripdata_2018-01.csv.gz,143211519,1596568992000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2018-02.csv.gz,yellow_tripdata_2018-02.csv.gz,139062994,1596568992000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2018-03.csv.gz,yellow_tripdata_2018-03.csv.gz,155108281,1596568994000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2018-04.csv.gz,yellow_tripdata_2018-04.csv.gz,153504004,1596568999000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2018-05.csv.gz,yellow_tripdata_2018-05.csv.gz,152775398,1596569003000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2018-06.csv.gz,yellow_tripdata_2018-06.csv.gz,144377468,1596569004000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2018-07.csv.gz,yellow_tripdata_2018-07.csv.gz,129810520,1596569004000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2018-08.csv.gz,yellow_tripdata_2018-08.csv.gz,129874126,1596569007000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2018-09.csv.gz,yellow_tripdata_2018-09.csv.gz,133683366,1596569012000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2018-10.csv.gz,yellow_tripdata_2018-10.csv.gz,146678859,1596569015000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2018-11.csv.gz,yellow_tripdata_2018-11.csv.gz,135364951,1596569015000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2018-12.csv.gz,yellow_tripdata_2018-12.csv.gz,135612832,1596569017000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2019-01.csv.gz,yellow_tripdata_2019-01.csv.gz,126896536,1596569018000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2019-02.csv.gz,yellow_tripdata_2019-02.csv.gz,121172953,1596569022000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2019-03.csv.gz,yellow_tripdata_2019-03.csv.gz,135816827,1596569027000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2019-04.csv.gz,yellow_tripdata_2019-04.csv.gz,128774049,1596569027000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2019-05.csv.gz,yellow_tripdata_2019-05.csv.gz,131394988,1596569028000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2019-06.csv.gz,yellow_tripdata_2019-06.csv.gz,120767491,1596569029000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2019-07.csv.gz,yellow_tripdata_2019-07.csv.gz,109579693,1596569033000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2019-08.csv.gz,yellow_tripdata_2019-08.csv.gz,105492899,1596569037000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2019-09.csv.gz,yellow_tripdata_2019-09.csv.gz,114297190,1596569037000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2019-10.csv.gz,yellow_tripdata_2019-10.csv.gz,125220156,1596569037000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2019-11.csv.gz,yellow_tripdata_2019-11.csv.gz,119085913,1596569038000
dbfs:/databricks-datasets/nyctaxi/tripdata/yellow/yellow_tripdata_2019-12.csv.gz,yellow_tripdata_2019-12.csv.gz,119637211,1596569040000

In [0]:
# Copy the above data to your volume
# load to Pandas DF 
# 1. Data Profiling - describe()
# 2. ETL ........
# 3. Analytics - Agg, min, max, avg, Group-By....

In [0]:
sal_DF = df['salary'].mean()

In [0]:
print("The ave salary is : ", sal_DF)

The ave salary is :  60000.0

In [0]:
sal_by_dept_DF = df.groupby('department')['salary'].sum()

In [0]:
print(sal_by_dept_DF)

department
 HR        60000
IT         50000
finance    70000
Name: salary, dtype: int64

In [0]:
emp_data = {
    'Name':['Alice','Bob','John','Bob','John'],
    'Salary':[1097,123345,65976,1097,123345],
    'Dept': ['IT', 'Accounts', 'HR','IT', 'Accounts'],
    'Bonus':[500,340, 100,356,9870]
}

In [0]:
emp_DF = pd.DataFrame(emp_data)

In [0]:
emp_DF

    Name  Salary      Dept  Bonus
0  Alice    1097        IT    500
1    Bob  123345  Accounts    340
2   John   65976        HR    100
3    Bob    1097        IT    356
4   John  123345  Accounts   9870

In [0]:
sal_by_dept_DF = emp_DF.groupby('Dept')['Salary'].sum()

In [0]:
print(sal_by_dept_DF)

Dept
Accounts    246690
HR           65976
IT            2194
Name: Salary, dtype: int64

In [0]:
%fs ls dbfs:/databricks-datasets/retail-org/

path,name,size,modificationTime
dbfs:/databricks-datasets/retail-org/README.md,README.md,1678,1602776043000
dbfs:/databricks-datasets/retail-org/active_promotions/,active_promotions/,0,1775812586701
dbfs:/databricks-datasets/retail-org/company_employees/,company_employees/,0,1775812586701
dbfs:/databricks-datasets/retail-org/customers/,customers/,0,1775812586701
dbfs:/databricks-datasets/retail-org/loyalty_segments/,loyalty_segments/,0,1775812586701
dbfs:/databricks-datasets/retail-org/products/,products/,0,1775812586701
dbfs:/databricks-datasets/retail-org/promotions/,promotions/,0,1775812586701
dbfs:/databricks-datasets/retail-org/purchase_orders/,purchase_orders/,0,1775812586701
dbfs:/databricks-datasets/retail-org/sales_orders/,sales_orders/,0,1775812586701
dbfs:/databricks-datasets/retail-org/sales_stream/,sales_stream/,0,1775812586701
dbfs:/databricks-datasets/retail-org/solutions/,solutions/,0,1775812586701
dbfs:/databricks-datasets/retail-org/suppliers/,suppliers/,0,1775812586701

In [0]:
%fs ls dbfs:/databricks-datasets/retail-org/products/

path,name,size,modificationTime
dbfs:/databricks-datasets/retail-org/products/products.csv,products.csv,12506,1602776044000

In [0]:
df = pd.read_csv('/databricks-datasets/retail-org/products/products.csv', delimiter= ';')
df

              product_id product_category  ...   EAN5  product_unit
0   AV1YFjNZglJLPUi8IGc8          Sioneer  ...  54984           pcs
1   AVpe48Es1cnluZ0-ZHZU           Zamaha  ...  54985           pcs
2   AVpe6-C2LJeJML43yWf1          Ramsung  ...  54986           pcs
3   AVpe6jFBilAPnD_xQxO2      Olitscreens  ...  54987           pcs
4   AVpe77ZXLJeJML43ysuz             Rony  ...  54988           pcs
..                   ...              ...  ...    ...           ...
93  AVwjhoD2v8e3D1O-nnNv            Ankyo  ...  55077           pcs
94  AVz5wc0H-jtxr-f30F6_           Zamaha  ...  55078           pcs
95  AVz5wclz-jtxr-f30F66          Sioneer  ...  55079           pcs
96  AVz5wcrn-jtxr-f30F69           Zamaha  ...  55080           pcs
97  AVzxl9XGvKc47QAVfStn            Opple  ...  55081           pcs

[98 rows x 7 columns]

In [0]:
sales_price_stats = df['sales_price'].agg(['min', 'max', 'mean', 'sum', 'count', 'std', 'median'])
display(sales_price_stats)

min          17.934000
max        3937.802308
mean        432.900777
sum       42424.276100
count        98.000000
std         609.222360
median      228.225245
Name: sales_price, dtype: float64

In [0]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 98 entries, 0 to 97
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   product_id        98 non-null     object
 1   product_category  98 non-null     object
 2   product_name      98 non-null     object
 3   sales_price       98 non-null     float64
 4   EAN13             98 non-null     int64
 5   EAN5              98 non-null     int64
 6   product_unit      98 non-null     object
dtypes: float64(1), int64(2), object(4)
memory usage: 5.5+ KB

In [0]:
df.isnull().sum

<bound method DataFrame.sum of     product_id  product_category  product_name  ...  EAN13   EAN5  product_unit
0        False             False         False  ...  False  False         False
1        False             False         False  ...  False  False         False
2        False             False         False  ...  False  False         False
3        False             False         False  ...  False  False         False
4        False             False         False  ...  False  False         False
..         ...               ...           ...  ...    ...    ...           ...
93       False             False         False  ...  False  False         False
94       False             False         False  ...  False  False         False
95       False             False         False  ...  False  False         False
96       False             False         False  ...  False  False         False
97       False             False         False  ...  False  False         False

[98 rows x 7 columns]>

In [0]:
df.describe()

       sales_price         EAN13          EAN5
count    98.000000  9.800000e+01     98.000000
mean    432.900777  2.198123e+12  55032.500000
std     609.222360  2.839008e+02     28.434134
min      17.934000  2.198123e+12  54984.000000
25%      95.984095  2.198123e+12  55008.250000
50%     228.225245  2.198123e+12  55032.500000
75%     462.231071  2.198123e+12  55056.750000
max    3937.802308  2.198123e+12  55081.000000

In [0]:
df.head()

             product_id product_category  ...   EAN5  product_unit
0  AV1YFjNZglJLPUi8IGc8          Sioneer  ...  54984           pcs
1  AVpe48Es1cnluZ0-ZHZU           Zamaha  ...  54985           pcs
2  AVpe6-C2LJeJML43yWf1          Ramsung  ...  54986           pcs
3  AVpe6jFBilAPnD_xQxO2      Olitscreens  ...  54987           pcs
4  AVpe77ZXLJeJML43ysuz             Rony  ...  54988           pcs

[5 rows x 7 columns]